[package]
name = "svgfixer"
version = "0.1.0"
authors = ["callum sykes <callum@mcneel.com"]
keywords = ["svg", "fixer"]
license = "GPL-2.0"
description = "Fixes issues with SVGs before they are fed into the cleaner"
documentation = "https://github.com/mcneel/svgcleaner/fixer/README.md"
repository = "https://github.com/mcneel/svgcleaner"
readme = "../README.md"
edition = "2024"

[lib]
name = "svgcleaner"
path = "src/lib.rs"
doctest = false

[[bin]]
doc = false
name = "svgfixer"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
regex = "1.11.1"

[dev-dependencies]
pretty_assertions = "1.4.1"