name: build

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Fixer
    - name: Build
      run: cargo build --manifest-path fixer/Cargo.toml --verbose
    
    - name: Run tests
      run: cargo test --manifest-path fixer/Cargo.toml --verbose

    # Cleaner
    - name: Build
      run: cargo build --manifest-path cleaner/Cargo.toml --verbose
    
    - name: Run tests
      run: cargo test --manifest-path cleaner/Cargo.toml --verbose
